// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nomina_API.Data;

#nullable disable

namespace Nomina_API.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20240626030618_ini")]
    partial class ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedModels.Deduccion", b =>
                {
                    b.Property<int>("DeduccionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeduccionID"));

                    b.Property<string>("ConceptoOD")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("INSS")
                        .HasColumnType("float");

                    b.Property<double>("IR")
                        .HasColumnType("float");

                    b.Property<double>("MontoOtrasDeducciones")
                        .HasColumnType("float");

                    b.Property<int>("NumeroEmpleado")
                        .HasColumnType("int");

                    b.Property<double>("TotalDeducciones")
                        .HasColumnType("float");

                    b.HasKey("DeduccionID");

                    b.HasIndex("NumeroEmpleado");

                    b.ToTable("Deducciones");
                });

            modelBuilder.Entity("SharedModels.Empleado", b =>
                {
                    b.Property<int>("NumeroEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroEmpleado"));

                    b.Property<int>("Celular")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EstadoEmpleado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaCierreContrato")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaContratacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("NumeroCedula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroINSS")
                        .HasColumnType("int");

                    b.Property<string>("NumeroRUC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<int>("YearsTrabajados")
                        .HasColumnType("int");

                    b.HasKey("NumeroEmpleado");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SharedModels.Ingreso", b =>
                {
                    b.Property<int>("IngresoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngresoID"));

                    b.Property<double>("Antiguedad")
                        .HasColumnType("float");

                    b.Property<string>("ConceptoOtrosIngresos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("HorasExtras")
                        .HasColumnType("float");

                    b.Property<double>("Nocturnidad")
                        .HasColumnType("float");

                    b.Property<int>("NumeroEmpleado")
                        .HasColumnType("int");

                    b.Property<double>("OtrosIngresos")
                        .HasColumnType("float");

                    b.Property<double>("RiesgoLaboral")
                        .HasColumnType("float");

                    b.Property<double>("SalarioOrdinario")
                        .HasColumnType("float");

                    b.Property<double>("TotalIngresos")
                        .HasColumnType("float");

                    b.HasKey("IngresoID");

                    b.HasIndex("NumeroEmpleado");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("SharedModels.Nomina", b =>
                {
                    b.Property<int>("NominaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NominaID"));

                    b.Property<DateOnly>("FechaNomina")
                        .HasColumnType("date");

                    b.Property<int>("NumeroEmpleado")
                        .HasColumnType("int");

                    b.Property<double>("SalarioNeto")
                        .HasColumnType("float");

                    b.HasKey("NominaID");

                    b.HasIndex("NumeroEmpleado");

                    b.ToTable("Nominas");
                });

            modelBuilder.Entity("SharedModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SharedModels.Deduccion", b =>
                {
                    b.HasOne("SharedModels.Empleado", "Empleado")
                        .WithMany("Deducciones")
                        .HasForeignKey("NumeroEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SharedModels.Ingreso", b =>
                {
                    b.HasOne("SharedModels.Empleado", "Empleado")
                        .WithMany("Ingresos")
                        .HasForeignKey("NumeroEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SharedModels.Nomina", b =>
                {
                    b.HasOne("SharedModels.Empleado", "Empleado")
                        .WithMany("Nominas")
                        .HasForeignKey("NumeroEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SharedModels.Empleado", b =>
                {
                    b.Navigation("Deducciones");

                    b.Navigation("Ingresos");

                    b.Navigation("Nominas");
                });
#pragma warning restore 612, 618
        }
    }
}
